# Generated by Django 5.2 on 2025-04-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_foodorder_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('coupon_code', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
