# Generated by Django 5.2 on 2025-04-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_couponsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('coupon_code', models.CharField(max_length=50)),
                ('offer_name', models.CharField(default='Default Offer', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CouponSubmission',
        ),
    ]
