# Generated by Django 5.2 on 2025-04-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_couponclaim_delete_couponsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponClaim',
            new_name='CouponSubmission',
        ),
    ]
