# Generated by Django 5.2 on 2025-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_couponclaim_couponsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsubmission',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='couponsubmission',
            name='offer_name',
            field=models.CharField(max_length=100),
        ),
    ]
