from django.urls import path
from . import views
from .views import feedback_view

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('archive/', views.archive, name='archive'),
    path('booking/', views.booking, name='booking'),
    path('contact/', views.contact, name='contact'),
    path('feature/', views.feature, name='feature'),
    path('menu/', views.menu, name='menu'),
    # path('order/', views.order_now, name='order_now'),
    path('offers/',views.offers, name='offers'),
    path('popup/', views.popup, name='popup'),
    path('popup2/', views.popup2, name='popup2'),
    path('read-more/', views.read_more, name='read_more'),
    path('team/', views.team, name='team'),
    # path('user_info/',views.user_info, name='user_info'),
    # path('user_info/', views.submit_coupon, name='user_info'),
     path('submit-user-info/', views.submit_user_info, name='submit_user_info'),
    path('coupon-success/', views.coupon_success, name='coupon_success'),
    path('coupon-proof/<int:submission_id>/', views.coupon_proof, name='coupon_proof'),
    path('privacy policy/', views.privacy_policy, name='privacy policy'),
   path('terms of cuse/', views.terms_of_use, name='terms_of_use'),
    path('FAQ/',views.FAQ, name='FAQ'),
    path('help/',views.help, name='help'),
    path('feedback/', feedback_view, name='feedback'),
   path('booking/', views.booking, name='booking'),
path('book/', views.booking_view, name='booking'),
path('booking-receipt/<int:booking_id>/', views.booking_receipt_view, name='booking_receipt'),
path('payment/<int:booking_id>/', views.payment_view, name='payment'),
path('payment-receipt/<int:booking_id>/', views.payment_receipt_view, name='payment_receipt'),
path('booking-receipt/pdf/<int:booking_id>/', views.booking_pdf_view, name='booking_pdf'),
path('payment-receipt/pdf/<int:booking_id>/', views.payment_pdf_view, name='payment_pdf'),
    path('food order/', views.food_order, name='food_order'),
    # path('order/', views.place_order, name='place_order'),
    path('order/', views.process_order, name='place_order'),
#    path('place-order/', views.place_order, name='place_order'),
#     path('receipt/<int:order_id>/', views.order_receipt, name='order_receipt'),
path('process_order/', views.process_order, name='process_order'),
path('receipt/<int:order_id>/', views.receipt, name='receipt'),
path('offers/', views.offer_page, name='offers'),
  path('user_info/', views.user_info, name='user_info'),
    path('coupon_proof/<int:submission_id>/', views.coupon_proof, name='coupon_proof'),
    path('coupon_success/', views.coupon_success, name='coupon_success'),

    # path('booking-receipt/<int:booking_id>/', views.booking_receipt, name='booking_receipt'),
    # path('receipt/<int:booking_id>/download/', views.download_pdf, name='download_pdf'),
    # path('receipt/pdf/<int:booking_id>/', views.generate_pdf, name='generate_pdf'),

]